version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper-test:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka-test:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper-test
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-test:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092

  kafka-setup:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - kafka-test
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "sleep 15 && kafka-topics --bootstrap-server kafka-test:9092 --create --if-not-exists --topic bank-transactions --replication-factor 1 && echo Done"

  server-test:
    build: ./server
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://test_user:test_password@postgres-test:5432/test_db
      KAFKA_BOOTSTRAP_SERVERS: kafka-test:9092
    depends_on:
      postgres-test:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully

  consumer-test:
    build: ./consumer
    environment:
      DATABASE_URL: postgresql+asyncpg://test_user:test_password@postgres-test:5432/test_db
      KAFKA_BOOTSTRAP_SERVERS: kafka-test:9092
    depends_on:
      - postgres-test
      - kafka-setup
      - server-test